name: CI

on:
  push:
    branches:
      - 'main'
      - 'release-v**'
      - 'full-sonar-analysis-**'
      - 'test/common-workflows' # to remove
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  pull_request:

permissions: { }

jobs:
  build:
    name: Build OS ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: github.event.pull_request.head.repo.fork == false
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout, set up JDK 21, build with Maven and Run SonarCloud analysis
        uses: powsybl/github-ci/setup-java-maven-sonar@89027772071d7d59d8c00c95446535678c7700d3
        with:
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          sonar_projectKey: 'com.powsybl:powsybl-afs'