name: Snapshot CI

on:
  workflow_dispatch:
  schedule:
    - cron: '20 3 * * *'

jobs:
  build_powsybl_afs:
    name: Build Java ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: false
    defaults:
      run:
        shell: bash

    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'temurin'
          java-version: '21'

      # Define script path variable
      - name: Set up script path
        run: |
          SCRIPTS_PATH="${GITHUB_WORKSPACE}/scripts/.github/workflows/scripts"
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            SCRIPTS_PATH=$(echo "$SCRIPTS_PATH" | sed 's/\\/\//g')
          fi
          echo "SCRIPTS_PATH=$SCRIPTS_PATH" >> $GITHUB_ENV  

      # Build powsybl-core on main branch
      - name: Checkout core sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: powsybl/powsybl-core
          ref: main
          path: powsybl-core

      - name: Build powsybl-core
        run: mvn -batch-mode --no-transfer-progress clean install -DskipTests
        working-directory: ./powsybl-core

      - name: Get powsybl-core version
        run: echo "CORE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
        working-directory: ./powsybl-core

      # Checkout script
      # The script check_snapshot_branch.sh is located in the workflow folder of the repository
      # It is necessary for checking out the integration branch if it exists
      - name: Checkout script
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
         sparse-checkout: |
           .github
         sparse-checkout-cone-mode: false
         path: scripts

      # Build powsybl-afs
      - name: Checking for powsybl-afs snapshot branch
        run: ${{ env.SCRIPTS_PATH }}/check_snapshot_branch.sh "https://github.com/powsybl/powsybl-afs.git" ${{ env.CORE_VERSION }}

      - name: Checkout powsybl-afs
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: powsybl/powsybl-afs
          ref: ${{ env.SNAPSHOT_BRANCH }}
          path: powsybl-afs
          submodules: true

      - name: update pom.xml
        run: mvn versions:set-property -Dproperty=powsyblcore.version -DnewVersion=$CORE_VERSION -DgenerateBackupPoms=false
        working-directory: ./powsybl-afs

      - name: Build with Maven (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        working-directory: ./powsybl-afs
        run: ./mvnw --batch-mode -Pjacoco install

      - name: Build with Maven (Windows)
        if: matrix.os == 'windows-latest'
        working-directory: .\powsybl-afs
        run: mvnw.cmd --batch-mode install
        shell: cmd

      - name: Store job result
        if: always()
        run: |
          echo "${{ matrix.os }}=${{ job.status }}" >> job_result_${{ matrix.os }}.txt

      - name: Upload job result
        if: always()
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # 7.0.0
        with:
          name: job-results_${{ matrix.os }}
          path: job_result_${{ matrix.os }}.txt

    outputs:
      core-version: ${{ env.CORE_VERSION }}
      afs-branch: ${{ env.SNAPSHOT_BRANCH }}

  # Slack notification
  notify_slack:
    needs: build_powsybl_afs
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Download job results
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1

      - name: Combine job results
        run: |
          for dir in job-results_*; do
            cat "$dir"/* >> combined_job_results.txt
          done

      - name: Determine workflow status
        id: workflow_status
        run: |
          if grep -q "failure" combined_job_results.txt; then
            echo "icon=❌" >> $GITHUB_OUTPUT
            echo "status=Failed" >> $GITHUB_OUTPUT
          else
            echo "icon=✅" >> $GITHUB_OUTPUT
            echo "status=Successful" >> $GITHUB_OUTPUT
          fi

      - name: Format job results
        id: format_results
        run: |
          formatted=""
          while IFS='=' read -r os status; do
            icon=$([ "$status" == "success" ] && echo ":white_check_mark:" || echo ":x:")
            formatted+="${icon} Build powsybl-afs on *${os}*\\n"
          done < combined_job_results.txt
          formatted="${formatted%\\n}"  # Remove the last newline
          echo "formatted_results=${formatted}" >> $GITHUB_OUTPUT

      - name: Prepare Slack payload
        id: prepare_payload
        run: |
          if [ "${{ steps.workflow_status.outputs.status }}" == "Successful" ]; then
            echo 'payload<<EOF' >> $GITHUB_OUTPUT
            echo '{
              "attachments": [{
                "color": "#319f4b",
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "${{ steps.workflow_status.outputs.icon }} *${{ steps.workflow_status.outputs.status }} workflow: Snapshot-CI on <https://github.com/powsybl/powsybl-afs|powsybl-afs>*\n\nBranch built: ${{ needs.build_powsybl_afs.outputs.afs-branch }}\nPowSyBl-Core version used: ${{ needs.build_powsybl_afs.outputs.core-version }}\n\nSee logs on <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|GitHub>"
                    }
                  }
                ]
              }]
            }' >> $GITHUB_OUTPUT
            echo 'EOF' >> $GITHUB_OUTPUT
          else
            echo 'payload<<EOF' >> $GITHUB_OUTPUT
            echo '{
              "attachments": [{
                "color": "#f64538",
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "${{ steps.workflow_status.outputs.icon }} *${{ steps.workflow_status.outputs.status }} workflow: Snapshot-CI on <https://github.com/powsybl/powsybl-afs|powsybl-afs>*\n\nBranch built: ${{ needs.build_powsybl_afs.outputs.afs-branch }}\nPowSyBl-Core version used: ${{ needs.build_powsybl_afs.outputs.core-version }}"
                    }
                  },
                  {
                    "type": "divider"
                  },
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "*Workflow details:*\n\n${{ steps.format_results.outputs.formatted_results }}\n\n@channel - See logs on <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|GitHub>"
                    }
                  }
                ]
              }]
            }' >> $GITHUB_OUTPUT
            echo 'EOF' >> $GITHUB_OUTPUT
          fi

      - name: Send Slack Notification
        uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1
        if: ${{ steps.workflow_status.outputs.status != 'Successful' || github.event_name == 'workflow_dispatch' }}
        with:
          webhook: ${{ secrets.SLACK_POWSYBL_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: ${{ steps.prepare_payload.outputs.payload }}
